version: '2'
services:
    runningapp-app:
        image: runningapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://runningapp-mysql:3306/runningapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    runningapp-mysql:
        extends:
            file: mysql.yml
            service: runningapp-mysql
